// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FooterPlay: typeof import('./src/components/ItemMusic/FooterPlay.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconList: typeof import('./src/components/home/IconList.vue')['default']
    MusicDetail: typeof import('./src/components/ItemMusic/MusicDetail.vue')['default']
    MusicList: typeof import('./src/components/home/MusicList.vue')['default']
    MusicPopup: typeof import('./src/components/ItemMusic/MusicPopup.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/video/Skeleton.vue')['default']
    SkeletonVideo: typeof import('./src/components/SkeletonVideo.vue')['default']
    TopNav: typeof import('./src/components/home/TopNav.vue')['default']
    TopSwiper: typeof import('./src/components/home/TopSwiper.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VideoDetail: typeof import('./src/components/video/VideoDetail.vue')['default']
  }
}

export {}
